Real-Dev-Squad/skill-tree-backend

skill-tree /pom.xml
skill-tree /src/main/java/com/RDS/skilltree/Skill.java
skill-tree /src/main/java/com/RDS/skilltree/SkillTreeApplication.java
skill-tree /src/main/java/com/RDS/skilltree/model/Skill.java
skill-tree /src/main/java/com/RDS/skilltree/repository/SkillRepository.java
skill-tree /src/main/resources/application.properties

Database setup

---

skill-tree /src/main/java/com/RDS/skilltree/Endorsement/EndorsementModel.java
skill-tree /src/main/java/com/RDS/skilltree/EndorsementList/EndorsementListModel.java
skill-tree /src/main/java/com/RDS/skilltree/Skill/SkillModel.java
skill-tree /src/main/java/com/RDS/skilltree/User/UserModel.java
skill-tree /src/main/java/com/RDS/skilltree/User/UserType.java

Date: 24Nov 23
Developer Name: @bhtibrewal 
----
-   Closes #44 
Updated the Models to match our schema 
add default user role and skill type 
-   [ ] Yes
-   [x] No
_If your feature adds a new API, then documentation related to the feature like API-Contracts, and Data-models must be updated._
-   [] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [x] Yes
-   [ ] No
**Under Feature Flag**
-   [x] Yes
-   [ ] No
_Specify if the changes are …

update endorsement model

---

.dockerignore
compose.yaml

-   Add the relevant issue ticket number here (e.g., Closes #<issue_number>).
Added a compose file, which starts MySQL, with the default users and data bas
-   [ ] Yes
-   [x] No
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No
**Under Feature Flag**
-   [ ] Yes
-   [x] No
_Specify if …

Add Docker compose file

---

api-contracts.yml

Date: 12th dec
Developer Name: @vikhyat187 
----
-   Add the relevant issue ticket number here (e.g., Closes #<issue_number>).
Provide a concise description of the changes made in this PR.
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [x] No
**Under Feature Flag**
- …

Updated the API contracts for finding skills with skill Name

---

.gitignore
skill-tree /src/main/java/com/RDS/skilltree/Endorsement/EndorsementController.java
skill-tree /src/main/java/com/RDS/skilltree/Endorsement/EndorsementService.java
skill-tree /src/main/resources/application.properties

- #46 
Create `GET api/v1/endorsement` route for getting list of endorsment
-   [ ] Yes
-   [x] No
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No
**Under Feature Flag**
-   [ ] Yes
-   [x] No
_Specify if the changes are currently under a feature flag._
**Database Changes**
-   [ ] Yes …

Get `/endorsment`

---

skill-tree /src/test/java/com/RDS/skilltree/unit/EndorsementServiceTest.java

Date: 19th Dec
Developer Name: Vikhyat
----
-   Add the relevant issue ticket number here (e.g., Closes #67 ).
After the migration of the tests to Junit 5, few Endorsement tests started failing
-   [ ] Yes
-   [x] No
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No
**Under Feature …

Fixed the Endorsement unit tests

---

skill-tree /src/main/java/com/RDS/skilltree/Skill/SkillsController.java
skill-tree /src/test/java/com/RDS/skilltree/SkillsIntegrationTests.java

Date: 19th Dec
Developer Name: Vikhyat
----
-   Add the relevant issue ticket number here (e.g., Closes #68).
Making the paginated api params consistent across APIs, example the page, size variable used in diff apis have diff names, make them consistent.
-   [ ] Yes
-   [x] No
-   [ ] Yes
-   [x] No
-   [x] Yes
-   [ ] No
-   [ ] Yes
-   [x] No
_Indicate whether the changes have …

Changing the paginated API default size and tests

---

.github/workflows/ci.yml

Date: 22nd Dec
Developer Name:  Vikhyat
----
-   Add the relevant issue ticket number here (e.g., Closes #71).
This change has been done, as we have removed the white space which was present in the folder name of the repo.

Correcting the pom.xml file path in github actions

---

skill-tree/src/main/resources/application.properties

Date: 21/1/24
Developer Name: 
---
https://github.com/Real-Dev-Squad/skill-tree-backend/issues/86
add port MYSQL_PORT var to use for staging deploy
No breaking changes, so no documentation or test needed.
<details>
</details>
<details>
</details>

add MYSQL_PORT var to application.properties

---

api-contracts.yml
skill-tree/src/main/java/com/RDS/skilltree/Endorsement/EndorsementModelFromJSON.java
skill-tree/src/main/java/com/RDS/skilltree/Endorsement/EndorsementService.java
skill-tree/src/main/java/com/RDS/skilltree/Endorsement/EndorsementServiceImpl.java
skill-tree/src/main/resources/dummy-date/endorsements.json

Date:  15 Mar 2024
Developer(s) Name:  @akhilkh2000 (Akhil khubchandani)
---
#95(feature)
Boilerplate code and data setup for v1 - search endorsements 
<details>
<summary>NA</summary>
</details>
<details>
<summary>NA </summary>
</details>
This is a setup PR for tests to be unblocked and basic data to be merged in. This will be followed up with the tests and  implementation PRs

Added boilerplate code and data, updated api-contract

---

skill-tree/src/main/java/com/RDS/skilltree/Config/SecurityConfig.java
skill-tree/src/main/java/com/RDS/skilltree/Config/WebMvcConfig.java
skill-tree/src/main/java/com/RDS/skilltree/Endorsement/EndorsementController.java
skill-tree/src/main/java/com/RDS/skilltree/Endorsement/EndorsementServiceImpl.java
skill-tree/src/main/java/com/RDS/skilltree/utils/GlobalExceptionHandler.java
skill-tree/src/main/java/com/RDS/skilltree/utils/UUIDValidationInterceptor.java
skill-tree/src/main/resources/application.properties
skill-tree/src/test/java/com/RDS/skilltree/integration/EndorsementsIntegrationTests.java
skill-tree/src/test/java/com/RDS/skilltree/unit/EndorsementServiceTest.java

Date: 19 March 2024
Developer Name: Akhil Khubchandani
---
#95 
Adding implementation for the search endorsement V1 feature #95 
This is the implementation PR following the test PRs - #108 and #107 .
- [] No
Example Response
This is the test coverage for the functionality in scope of this PR for which @Chethan64  has written tests: 
(@Chethan64  - confirmed on this) 
Have enabled the relevant tests that were originally disabled in the test PRs - #108 and #107

Added implementation for V1 search endorsements based on dummy data and enabled tests

---

api-contracts.yml
skill-tree/src/main/java/com/RDS/skilltree/Endorsement/EndorsementController.java
skill-tree/src/main/java/com/RDS/skilltree/Endorsement/EndorsementService.java
skill-tree/src/main/java/com/RDS/skilltree/Endorsement/EndorsementServiceImpl.java
skill-tree/src/main/java/com/RDS/skilltree/Endorsement/EndorsementStatus.java
skill-tree/src/main/java/com/RDS/skilltree/utils/CommonUtils.java
skill-tree/src/main/java/com/RDS/skilltree/utils/GlobalExceptionHandler.java
skill-tree/src/main/java/com/RDS/skilltree/utils/UUIDValidationInterceptor.java

Date: 14 April 2024
Developer Name: Atif Siddiqui @Atifsid
---
#45 
Create accept/reject endorsement (Super User only API)
Tests are added in #117 for this feature.
<details>
</details>
<details>
</details>
~I will add tests in future, If this pr becomes big then I will raise another pr and mention here.~
~Currently, Integration tests are failing due to `create endorsement feature`~
This pr will go after #117

feat: create approve/reject endorsement

---

Makefile
docker/dev-docker-compose.yaml

- Create a dev docker-compose file to setup mysql database for development

create a make file and dev docker compose file to setup database for development

---

.github/workflows/deploy-to-ec2.yml

Deploy to AWS
<details>
</details>
<details>
</details>

AWS staging delpoy script

---

skill-tree/src/main/java/com/RDS/skilltree/apis/EndorsementsApi.java
skill-tree/src/main/java/com/RDS/skilltree/apis/SkillsApi.java
skill-tree/src/main/java/com/RDS/skilltree/dtos/CreateEndorsementRequestDto.java
skill-tree/src/main/java/com/RDS/skilltree/dtos/RdsGetUserDetailsResDto.java
skill-tree/src/main/java/com/RDS/skilltree/viewmodels/CreateEndorsementViewModel.java

Date: 
Developer Name: 
---
<details>
</details>
<details>
</details>

Refactor: Move post endorsements in skills route

---

.github/workflows/deploy-to-ec2.yml

https://github.com/Real-Dev-Squad/skill-tree-backend/issues/127 
Passes envs in CI scripts
<details>
</details>
<details>
</details>

Add envs in CI script

---

.github/workflows/deploy-to-ec2.yml

https://github.com/Real-Dev-Squad/skill-tree-backend/issues/127
Add env URLs to CI script
<details>
</details>
<details>
</details>

Add URL envs to CI script

---

skill-tree/src/main/java/com/RDS/skilltree/apis/SkillsApi.java
skill-tree/src/main/java/com/RDS/skilltree/services/SkillService.java
skill-tree/src/main/java/com/RDS/skilltree/services/SkillServiceImplementation.java
skill-tree/src/main/java/com/RDS/skilltree/viewmodels/SkillRequestViewModel.java
skill-tree/src/main/java/com/RDS/skilltree/viewmodels/SkillRequestsWithUserDetailsViewModel.java

Date: 27th august 2024 
Developer Name: yash raj
- #150 
- add status filter to `v1/skills/requests` API

add status filter to get all skill requests api

---

skill-tree/src/main/java/com/RDS/skilltree/apis/SkillsApi.java
skill-tree/src/test/java/com/RDS/skilltree/skills/CreateSkillIntegrationTest.java

Date: 20 Feb 2025
Developer Name: Shyam Vishwakarma
---
- Closes: #178  
- Updated the status code from 200 (ok) to 201 (created) for the response after creating new skill
- Wrote integration test for `POST /v1/skills`
Document: [Link](https://docs.google.com/document/d/1byH5-kNcfIEAS2-6D0VvxON4XzOKCSosOQQ47zC8-a0/edit?usp=sharing)
<details>
</details>
<details>
Coverage for POST v1/skills:
All the methods and packages that are related to this route are being tested and covered in the report-
</details>
- If you face any error such as `skilltreetestdb not found`, then create a test database manually in your local using `create database skilltreetestdb;` (will add this in documentation asap)

Test: Integration Test for POST /v1/skills

---

skill-tree/src/main/resources/application-test.properties
skill-tree/src/test/java/com/RDS/skilltree/TestContainerManager.java
skill-tree/src/test/java/com/RDS/skilltree/integration/skills/CreateSkillIntegrationTest.java
skill-tree/src/test/java/com/RDS/skilltree/integration/skills/GetAllSkillRequestIntegrationTest.java
skill-tree/src/test/java/com/RDS/skilltree/integration/skills/GetAllSkillsIntegrationTest.java
skill-tree/src/test/java/com/RDS/skilltree/integration/skills/GetEndorsementsBySkillIdIntegrationTest.java
skill-tree/src/test/java/com/RDS/skilltree/integration/skills/SkillRequestActionIntegrationTest.java
skill-tree/src/test/java/utils/TestDataHelper.java

Date: 23 April 2025
Developer Name: @Shyam-Vishwakarma 
---
- Closes: 
- #179 
- #193 
- Wrote integration test for GET /v1/skills/{skillId}/endorsements
- Removed hardcoded value from test container manager
Document: [Link](https://docs.google.com/document/d/1sLpPk7vvxcFxfzcuvZhwNv0irstlZdltPkQeQL0t5VE/edit?tab=t.0)
<details>
Build success:
</details>
<details>
- Test coverage of all tests:
</details>
<details>
<summary>Screenshot 2</summary>
Coverage of tests for GET /v1/skills/{skillId}/endorsements only:
(Coverage is low because only those classes/methods are being executed that are related to this endpoint)
</details>
<details>
<summary>Screenshot 3</summary>
Test coverage filtered by classes and packages related to this …

test: integration test for GET /v1/skills/{skillId}/endorsements
